export const vehicles = [
  {
    id: 1,
    brand: "Mazda",
    model: "CX-30 Grand Touring Híbrida",
    year: 2023,
    price: 105900000,
    image: "/Disponibles/cx 30 hibrida 2023/cx30-hibrida-2023-portada.jpeg",
    mileage: "29,000 km",
    color: "Rojo Diamante",
    transmission: "Automática",
    engine: "2.0L Híbrido",
    fuelType: "Híbrido",
    sold: false,
    description:
      "La Mazda CX-30 Grand Touring Híbrida combina un diseño elegante con tecnología híbrida eficiente. Potencia, confort y bajo consumo en una SUV compacta de alto nivel.",
    images: [
      "/Disponibles/cx 30 hibrida 2023/cx30-hibrida-2023-portada.jpeg",
      "/Disponibles/cx 30 hibrida 2023/cx30-hibrida-2023-2.jpeg",
      "/Disponibles/cx 30 hibrida 2023/cx30-hibrida-2023-3.jpg",
      "/Disponibles/cx 30 hibrida 2023/cx30-hibrida-2023-4.jpeg",
      "/Disponibles/cx 30 hibrida 2023/cx30-hibrida-2023-5.jpeg",
      "/Disponibles/cx 30 hibrida 2023/cx30-hibrida-2023-6.jpg",
      "/Disponibles/cx 30 hibrida 2023/cx30-hibrida-2023-7.jpg",
      "/Disponibles/cx 30 hibrida 2023/cx30-hibrida-2023-8.jpg",
      "/Disponibles/cx 30 hibrida 2023/cx30-hibrida-2023-9.jpg",
      "/Disponibles/cx 30 hibrida 2023/cx30-hibrida-2023-10.jpeg",
    ],
  },
  {
    id: 2,
    brand: "Renault",
    model: "Duster 4x4",
    year: 2020,
    price: 62900000,
    image: "/Disponibles/duster 2020 4x4/duster2020-portada.jpg",
    mileage: "116,000 km",
    color: "Plata",
    transmission: "Mecánica",
    engine: "2.0L 4x4",
    fuelType: "Gasolina",
    sold: false,
    description:
      "La Renault Duster 4x4 es una SUV todo terreno potente y versátil. Con tracción en las cuatro ruedas y motor 2.0L, ofrece rendimiento sobresaliente tanto en ciudad como en terrenos exigentes.",
    images: [
      "/Disponibles/duster 2020 4x4/duster2020-portada.jpg",
      "/Disponibles/duster 2020 4x4/duster2020-2.jpg",
      "/Disponibles/duster 2020 4x4/duster2020-3.jpeg",
      "/Disponibles/duster 2020 4x4/duster2020-5.jpeg",
      "/Disponibles/duster 2020 4x4/duster2020-6.jpeg",
      "/Disponibles/duster 2020 4x4/duster2020-7.jpeg",
      "/Disponibles/duster 2020 4x4/duster2020-8.jpg",
      "/Disponibles/duster 2020 4x4/duster2020-9.jpeg",
      "/Disponibles/duster 2020 4x4/duster2020-10.jpeg",
      "/Disponibles/duster 2020 4x4/duster2020-11.jpeg",
    ],
  },
  {
    id: 3,
    brand: "Mazda",
    model: "CX-30 Touring",
    year: 2022,
    price: 96900000,
    image: "/Disponibles/Mazda cx 30 2022/cx30-portada.jpeg",
    mileage: "28,000 km",
    color: "Machine Gray",
    transmission: "Automática",
    engine: "2.0L",
    fuelType: "Gasolina",
    sold: false,
    description:
      "La Mazda CX-30 Touring es una SUV moderna que combina diseño sofisticado con tecnología avanzada. Ofrece confort, seguridad y una conducción dinámica para quienes buscan estilo y rendimiento en cada trayecto.",
    images: [
      "/Disponibles/Mazda cx 30 2022/cx30-portada.jpeg",
      "/Disponibles/Mazda cx 30 2022/cx30-portada2.jpeg",
      "/Disponibles/Mazda cx 30 2022/cx30-portada3.jpeg",
      "/Disponibles/Mazda cx 30 2022/cx30-frente.jpeg",
      "/Disponibles/Mazda cx 30 2022/cx30-izq.jpeg",
      "/Disponibles/Mazda cx 30 2022/cx30-interior.jpeg",
      "/Disponibles/Mazda cx 30 2022/cx30-manubrio.jpeg",
      "/Disponibles/Mazda cx 30 2022/cx30-llanta.jpeg",
      "/Disponibles/Mazda cx 30 2022/cx30-atras-der.jpeg",
      "/Disponibles/Mazda cx 30 2022/cx30-atras-izq.jpeg",
      "/Disponibles/Mazda cx 30 2022/cx30-palanca.jpeg",
    ],
  },
  {
    id: 4,
    brand: "Mazda",
    model: "Mazda 2 Grand Touring LX",
    year: 2023,
    price: 80900000,
    image: "/Disponibles/Mazda 2 2023/mazda2-p.jpg",
    mileage: "36,000 km",
    color: "Cuarzo platino",
    transmission: "Automática",
    engine: "1.5L Skyactiv",
    fuelType: "Gasolina",
    sold: false,
    description:
      "El Mazda 2 Grand Touring LX integra conectividad, seguridad y acabados de alta calidad en un formato compacto. Equilibrio perfecto entre rendimiento, eficiencia y experiencia de manejo.",
    images: [
      "/Disponibles/Mazda 2 2023/mazda2-p.jpg",
      "/Disponibles/Mazda 2 2023/m2-1.jpg",
      "/Disponibles/Mazda 2 2023/m2-2.jpg",
      "/Disponibles/Mazda 2 2023/m2-3.jpg",
      "/Disponibles/Mazda 2 2023/m2-4.jpg",
      "/Disponibles/Mazda 2 2023/m2-5.jpg",
      "/Disponibles/Mazda 2 2023/m2-06.jpg",
      "/Disponibles/Mazda 2 2023/m2-6.jpg",
      "/Disponibles/Mazda 2 2023/M2-7.jpg",
    ],
  },
  {
    id: 5,
    brand: "Renault",
    model: "Logan Familier",
    year: 2013,
    price: 27900000,
    image: "/Disponibles/Logan rojo/renault-logan-2013-portada.jpg",
    mileage: "129,000 km",
    color: "Rojo fuego",
    transmission: "Mecanica",
    engine: "1.4L",
    fuelType: "Gasolina",
    sold: false,
    description:
      "El Renault Logan es un sedán familiar amplio y confiable. Combina economía, comodidad y gran espacio interior, ideal para quienes buscan rendimiento diario sin sacrificar confort.",
    images: [
      "/Disponibles/Logan rojo/renault-logan-2013-portada.jpg",
      "/Disponibles/Logan rojo/renault-logan-2013-frente.jpg",
      "/Disponibles/Logan rojo/rlogan-2013-frente-derecha.jpg",
      "/Disponibles/Logan rojo/renault-logan-2013-cojineria.jpg",
      "/Disponibles/Logan rojo/rlogan2013-interior.jpg",
      "/Disponibles/Logan rojo/rlogan-2013-llanta.jpg",
      "/Disponibles/Logan rojo/renaultlogan2013-atras-derecha.jpg",
      "/Disponibles/Logan rojo/rlogan2013-atras-izq.jpg",
      "/Disponibles/Logan rojo/renault-logan-2013-trasera.jpg",
      "/Disponibles/Logan rojo/rlogan2013-lado.jpg",
      "/Disponibles/Logan rojo/rlogan2013-mitaddelantera.jpg",
    ],
  },
  {
    id: 6,
    brand: "Renault",
    model: "Duster Iconic",
    year: 2023,
    price: 79900000,
    image: "/Vendidos/Duster 2023/bduster-1.jpg",
    mileage: "50,000 km",
    color: "Blanco",
    transmission: "Mecánica",
    engine: "1.3L Turbo",
    fuelType: "Gasolina",
    sold: true,
    description:
      "La Renault Duster Iconic es una SUV robusta que combina diseño moderno con gran capacidad y rendimiento. Espacio, altura y potencia se unen para ofrecer seguridad y versatilidad en cualquier terreno.",
    images: [
      "/Vendidos/Duster 2023/bduster-1.jpg",
      "/Vendidos/Duster 2023/bduster-2.jpg",
      "/Vendidos/Duster 2023/bduster-3.jpg",
      "/Vendidos/Duster 2023/bduster-4.jpg",
      "/Vendidos/Duster 2023/bduster-05.jpg",
      "/Vendidos/Duster 2023/bduster-5.jpg",
      "/Vendidos/Duster 2023/bduster-6.jpg",
      "/Vendidos/Duster 2023/bduster-7.jpg",
    ],
  },
  {
    id: 7,
    brand: "Chevrolet",
    model: "NHR",
    year: 2023,
    price: 120900000,
    image: "/Vendidos/Nhr 2023/nhr-2.jpg",
    mileage: "38,000 km",
    color: "Blanco",
    transmission: "Mecánica",
    engine: "2.0L",
    fuelType: "Diesel",
    sold: true,
    description:
      "El Chevrolet NHR es una camioneta de carga liviana robusta y confiable, ideal para trabajo y transporte. Motor diésel eficiente con excelente capacidad de carga.",
    images: [
      "/Vendidos/Nhr 2023/nhr-2.jpg",
      "/Vendidos/Nhr 2023/nhr-3.jpg",
      "/Vendidos/Nhr 2023/nhr-4.jpg",
      "/Vendidos/Nhr 2023/nhr-5.jpg",
      "/Vendidos/Nhr 2023/nhr-6.jpg",
      "/Vendidos/Nhr 2023/nhr-7.jpg",
      "/Vendidos/Nhr 2023/nhr-8.jpg",
      "/Vendidos/Nhr 2023/nhr-9.jpg",
    ],
  },
]
