export const vehicles = [
  {
    id: 1,
    brand: "Renault",
    model: "Logan Familier",
    year: 2013,
    price: 27900000,
    image: "/Disponibles/renault-logan-2013-portada.jpg",
    mileage: "129,000 km",
    color: "Rojo fuego",
    transmission: "Mecanica",
    engine: "1.4L",
    fuelType: "Gasolina",
    sold: false,
    description:
      "El Renault Logan es un sedán familiar amplio y confiable. Combina economía, comodidad y gran espacio interior, ideal para quienes buscan rendimiento diario sin sacrificar confort.",
    images: [
      "/Disponibles/renault-logan-2013-portada.jpg",
      "/Disponibles/renault-logan-2013-frente.jpg",
      "/Disponibles/rlogan-2013-frente-derecha.jpg",
      "/Disponibles/renault-logan-2013-cojineria.jpg",
      "/Disponibles/rlogan2013-interior.jpg",
      "/Disponibles/rlogan-2013-llanta.jpg",
      "/Disponibles/renaultlogan2013-atras-derecha.jpg",
      "/Disponibles/rlogan2013-atras-izq.jpg",
      "/Disponibles/renault-logan-2013-trasera.jpg",
      "/Disponibles/rlogan2013-lado.jpg",
      "/Disponibles/rlogan2013-mitaddelantera.jpg",
    ],
  },
  {
    id: 2,
    brand: "Mazda",
    model: "CX-30 Touring",
    year: 2022,
    price: 96900000,
    image: "/Disponibles/cx30-portada.jpeg",
    mileage: "28,000 km",
    color: "Machine Gray",
    transmission: "Automática",
    engine: "2.0L",
    fuelType: "Gasolina",
    sold: false,
    description:
      "La Mazda CX-30 Touring es una SUV moderna que combina diseño sofisticado con tecnología avanzada. Ofrece confort, seguridad y una conducción dinámica para quienes buscan estilo y rendimiento en cada trayecto.",
    images: [
      "/Disponibles/cx30-portada.jpeg",
      "/Disponibles/cx30-portada2.jpeg",
      "/Disponibles/cx30-portada3.jpeg",
      "/Disponibles/cx30-frente.jpeg",
      "/Disponibles/cx30-izq.jpeg",
      "/Disponibles/cx30-interior.jpeg",
      "/Disponibles/cx30-manubrio.jpeg",
      "/Disponibles/cx30-llanta.jpeg",
      "/Disponibles/cx30-atras-der.jpeg",
      "/Disponibles/cx30-atras-izq.jpeg",
      "/Disponibles/cx30-palanca.jpeg",
    ],
  },
  {
    id: 3,
    brand: "Mazda",
    model: "Mazda 2 Grand Touring LX",
    year: 2023,
    price: 80900000,
    image: "/Disponibles/mazda2-p.jpg",
    mileage: "36,000 km",
    color: "Cuarzo platino",
    transmission: "Automática",
    engine: "1.5L Skyactiv",
    fuelType: "Gasolina",
    sold: false,
    description:
      "El Mazda 2 Grand Touring LX integra conectividad, seguridad y acabados de alta calidad en un formato compacto. Equilibrio perfecto entre rendimiento, eficiencia y experiencia de manejo.",
    images: [
      "/Disponibles/mazda2-p.jpg",
      "/Disponibles/m2-1.jpg",
      "/Disponibles/m2-2.jpg",
      "/Disponibles/m2-3.jpg",
      "/Disponibles/m2-4.jpg",
      "/Disponibles/m2-5.jpg",
      "/Disponibles/m2-06.jpg",
      "/Disponibles/m2-6.jpg",
      "/Disponibles/M2-7.jpg",
    ],
  },
  {
    id: 4,
    brand: "Renault",
    model: "Kwid Outsider",
    year: 2024,
    price: 44700000,
    image: "/Disponibles/kwid-por.jpg",
    mileage: "20,000 km",
    color: "Blanco",
    transmission: "Mecánica",
    engine: "1.0L",
    fuelType: "Gasolina",
    sold: false,
    description:
      "El Renault Kwid Outsider es un compacto moderno que combina diseño juvenil con gran eficiencia. Ágil, económico y versátil, es ideal para la ciudad y para quienes buscan practicidad en cada trayecto.",
    images: [
      "/Disponibles/kwid-por.jpg",
      "/Disponibles/kwid-1.jpg",
      "/Disponibles/kwid-2.jpg",
      "/Disponibles/kwid-3.jpg",
      "/Disponibles/kwid-4.jpg",
      "/Disponibles/kwid-5.jpg",
      "/Disponibles/kwid-6.jpg",
      "/Disponibles/kwid-7.jpg",
      "/Disponibles/kwid-8.jpg",
    ],
  },
  {
    id: 5,
    brand: "Renault",
    model: "Duster Iconic",
    year: 2023,
    price: 79900000,
    image: "/Vendidos/bduster-portada.jpg",
    mileage: "50,000 km",
    color: "Blanco",
    transmission: "Mecánica",
    engine: "1.3L Turbo",
    fuelType: "Gasolina",
    sold: true,
    description:
      "La Renault Duster Iconic es una SUV robusta que combina diseño moderno con gran capacidad y rendimiento. Espacio, altura y potencia se unen para ofrecer seguridad y versatilidad en cualquier terreno.",
    images: [
      "/Vendidos/bduster-portada.jpg",
      "/Vendidos/bduster-1.jpg",
      "/Vendidos/bduster-2.jpg",
      "/Vendidos/bduster-3.jpg",
      "/Vendidos/bduster-4.jpg",
      "/Vendidos/bduster-05.jpg",
      "/Vendidos/bduster-5.jpg",
      "/Vendidos/bduster-6.jpg",
      "/Vendidos/bduster-7.jpg",
    ],
  },
  {
    id: 6,
    brand: "Chevrolet",
    model: "NHR",
    year: 2023,
    price: 120900000,
    image: "/Vendidos/nhr-portada.jpg",
    mileage: "38,000 km",
    color: "Blanco",
    transmission: "Mecánica",
    engine: "2.0L",
    fuelType: "Diesel",
    sold: true,
    description:
      "El Chevrolet NHR es una camioneta de carga liviana robusta y confiable, ideal para trabajo y transporte. Motor diésel eficiente con excelente capacidad de carga.",
    images: [
      "/Vendidos/nhr-portada.jpg",
      "/Vendidos/nhr-2.jpg",
      "/Vendidos/nhr-3.jpg",
      "/Vendidos/nhr-4.jpg",
      "/Vendidos/nhr-5.jpg",
      "/Vendidos/nhr-6.jpg",
      "/Vendidos/nhr-7.jpg",
      "/Vendidos/nhr-8.jpg",
      "/Vendidos/nhr-9.jpg",
    ],
  },
]
