export const vehicles = [
  {
    id: 1,
    brand: "Renault",
    model: "Logan Familier",
    year: 2013,
    price: 27900000,
    image: "/renault-logan-2013-portada.jpg",
    mileage: "129,000 km",
    color: "Rojo fuego",
    transmission: "Mecanica",
    engine: "1.4L",
    fuelType: "Gasolina",
    description:
      "El Renault Logan es un sedán familiar amplio y confiable. Combina economía, comodidad y gran espacio interior, ideal para quienes buscan rendimiento diario sin sacrificar confort.",
    images: ["/renault-logan-2013-portada.jpg", "/renault-logan-2013-frente.jpg", "/rlogan-2013-frente-derecha.jpg", "/renault-logan-2013-cojineria.jpg", "/rlogan2013-interior.jpg", "/rlogan-2013-llanta.jpg", "/renaultlogan2013-atras-derecha.jpg", "/rlogan2013-atras-izq.jpg", "/renault-logan-2013-trasera.jpg"],
  },
  {
    id: 2,
    brand: "Mazda",
    model: "CX-30 Touring",
    year: 2022,
    price: 96900000,
    image: "/cx30-portada.jpeg",
    mileage: "28,000 km",
    color: "Machine Gray",
    transmission: "Automática",
    engine: "2.0L ",
    fuelType: "Gasolina",
    description:
      "La Mazda CX-30 Touring es una SUV moderna que combina diseño sofisticado con tecnología avanzada. Ofrece confort, seguridad y una conducción dinámica para quienes buscan estilo y rendimiento en cada trayecto.",
    images: ["/cx30-portada.jpeg", "/cx30-frente.jpeg", "/cx30-izq.jpeg", "/cx30-interior.jpeg", "/cx30-manubrio.jpeg", "/cx30-llanta.jpeg", "/cx30-atras-der.jpeg", "/cx30-atras-izq.jpeg", "/cx30-palanca.jpeg"],
  },
  {
    id: 3,
    brand: "Mazda",
    model: "Mazda 2 Grad Touring LX",
    year: 2023,
    price: 80900000,
    image: "/mazda2-p.jpg",
    mileage: "36,000 km",
    color: "Cuarzo platino",
    transmission: "Automática",
    engine: "1.5L Skyactiv",
    fuelType: "Gasolina",
    description:
      "El Mazda 2 Grand Touring LX integra conectividad, seguridad y acabados de alta calidad en un formato compacto. Equilibrio perfecto entre rendimiento, eficiencia y experiencia de manejo..",
    images: ["/mazda2-p.jpg", "/m2-1.jpg", "/m2-2.jpg", "/m2-3.jpg", "/m2-4.jpg", "/m2-5.jpg", "/m2-06.jpg", "/m2-6.jpg", "/M2-7.jpg"],
  },
  {
    id: 4,
    brand: "Renault",
    model: "Kwid Outsider",
    year: 2024,
    price: 44700000,
    image: "/kwid-por.jpg",
    mileage: "20,000 km",
    color: "Blanco",
    transmission: "Mecánica",
    engine: "1.0L",
    fuelType: "Gasolina",
    description:
      "El Renault Kwid Outsider es un compacto moderno que combina diseño juvenil con gran eficiencia. Ágil, económico y versátil, es ideal para la ciudad y para quienes buscan practicidad en cada trayecto.",
    images: ["/kwid-por.jpg", "/kwid-1.jpg", "/kwid-2.jpg", "/kwid-3.jpg", "/kwid-4.jpg", "/kwid-5.jpg", "/kwid-6.jpg", "/kwid-7.jpg", "/kwid-8.jpg"],
  },
  {
    id: 5,
    brand: "Renault",
    model: "Duster Iconic",
    year: 2023,
    price: 79900000,
    image: "/bduster-portada.jpg",
    mileage: "50,000 km",
    color: "Blanco",
    transmission: "Mecánica",
    engine: "1.3L Turbo",
    fuelType: "Gasolina",
    description:
      "La Renault Duster Iconic es una SUV robusta que combina diseño moderno con gran capacidad y rendimiento. Espacio, altura y potencia se unen para ofrecer seguridad y versatilidad en cualquier terreno.",
    images: [
      "/bduster-portada.jpg",
      "/bduster-1.jpg",
      "/bduster-2.jpg",
      "/bduster-3.jpg",
      "/bduster-4.jpg",
      "/bduster-05.jpg",
      "/bduster-5.jpg",
      "/bduster-6.jpg",
      "/bduster-7.jpg",
    ],
  },
  {
    id: 6,
    brand: "Chevrolet",
    model: "NHR",
    year: 2023,
    price: 120900000,
    image: "/nhr-portada.jpg",
    mileage: "38,000 km",
    color: "Blanco",
    transmission: "Mecánica",
    engine: "2.0L",
    fuelType: "Diesel",
    description:
      "El Ferrari F8 Tributo es un homenaje al motor V8 más potente de Ferrari. 720 HP de pura emoción italiana.",
    images: ["/nhr-portada.jpg", "/nhr-2.jpg", "/nhr-3.jpg"],
  },
]
